---
title: "Network_Stuff"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = "~/OneDrive - Universitaet Bern/NKC_project/R_scripts/") # set directory
```

I'm trying out some newwork stuff by following this statnet turorial https://statnet.org/workshop-intro-sna-tools/

### Set up workspace
```{r libraries}
#install.packages(c("network", "sna", "igraph", "tidygraph", "ggraph", 
#                   "intergraph", "remotes"))
#remotes::install_bioc("graph")

library(ggraph)
library(igraph)
library(gtools)
library(dplyr)

```



```{r}
# Making an adjacency matrix (which metagenotypes can mutate into each other?)
x <- as.data.frame(gtools::permutations(2, 4, c(1:2), repeats = TRUE))
x$ID <- 1:16

adj_mat <- matrix(16, 16, data = rep(0, 16^2))

for (i in 1:16) {
  
  adj_mat[i,findNeighbours(x, i, 4)$ID] <- 1
  
}

# the issue I have right now is, that technically the metagenotypes differe from the pov from the focal species I have at a given time -> need to stick to a single focal species
# turn out I don't actually need this rn

```


```{r}
# translating my adaptive walks into something I can use here (maybe?)
# I need to extract the transitions from my adaptive walks -> format: from - to - in how many replicates of walk


walks_dfs <- NULL
for (i in 1:48){
  
 temp_df <- peaks_nkcs_2111[[5]][[2]][[40]][[1]][[i]]
 
 IDs <- NULL
 
 for (j in 0:max(temp_df[[1]][,"step"])) {
   
    metagenotype <- temp_df[[1]][temp_df[[1]]$step == j, c("F.1", "F.2", "P.1", "P.2")]
 ID_temp <- x[rowSums(mapply(`==`, x[, c("V1", "V2", "V3", "V4")], metagenotype)) == 4, "ID"] # extract the ID of the metagenotype that matches my adjacency matrix IDs
 
 IDs <- c(IDs, ID_temp)
   
 }
 
 from_IDs <- IDs[1:(length(IDs)-1)]
 to_IDs <- IDs[2:length(IDs)]
 
 temp_df <- data.frame(from = from_IDs,
                       to = to_IDs,
                      step = temp_df[[1]][c(2:nrow(temp_df[[1]])),"step"],
                       focal = temp_df[[1]][c(2:nrow(temp_df[[1]])),"focal"],
                       walk = i)
 
 walks_dfs <- rbind(walks_dfs, temp_df)
  
}

walks_dfs_summed <- as.data.frame(walks_dfs |> 
                            dplyr::group_by(from, to, focal, walk) |>
                            dplyr::summarise(step_count = n()))

walks_dfs_summed2 <- as.data.frame(walks_dfs_summed |> 
                            dplyr::group_by(from, to, focal) |>
                            dplyr::summarise(rep_count = n())) # this gives me in how many replicates certain steps were taken from x to y given a certain focal species


```

```{r}

g <- igraph::graph_from_data_frame(walks_dfs_summed2, 
                           directed = TRUE)

# add metadata to the nodes in the network (here "averaged per node")
igraph::V(g)$count <- ave(walks_dfs_summed2$rep_count, walks_dfs_summed2$from, FUN = max)[match(V(g)$name, walks_dfs_summed2$from)]

ranks_sp1 <- peaks_nkcs_2111[[4]][[2]][[40]][[1]]$rank
test_df <- peaks_nkcs_2111[[4]][[2]][[40]][[2]]
ranks_sp2 <- test_df[order(test_df$P.1, test_df$P.2, test_df$F.1, test_df$F.2), "rank"]

igraph::V(g)$rank_sp1 <- ranks_sp1
igraph::V(g)$rank_sp2 <- ranks_sp2


graph <- ggraph::ggraph(g,
               layout = "stress") +
  geom_edge_fan(aes(linetype = as.factor(focal)), # different edge color for the different steps based on focal species
                 end_cap = circle(5, "mm"), # buffer between node and arrow
                colour = "grey40") + 
  geom_edge_fan(arrow = arrow(type = "closed", # make arrow heads separately so they all have solid outlines
                              angle = 20, # "width" of arrow tip
                              length = unit(4, "mm")), # length of arrow tip
                edge_width = 0,
                 end_cap = circle(5, "mm"), # buffer between node and arrow
                colour = "grey40") + 
  geom_edge_loop(aes(linetype = as.factor(focal),
                     strength = (3*focal/4)), # to make non-overlapping loops
                 end_cap = circle(4, "mm"),
                colour = "grey40") +
  geom_edge_loop(aes(strength = (3*focal/4)), # make arrow heads separately so they all have solid outlines
                 arrow = arrow(type = "closed",
                               angle = 20,
                 length = unit(4, "mm")),
                 edge_width = 0,
                 end_cap = circle(4, "mm"),
                colour = "grey40") +
  geom_node_arc_bar(aes(x0 = x,
                        y0 = y,
                        r0 = 0, 
                        r = count/300 + 0.1,
                       start = pi, 
                       end = 2*pi,
                       fill = rank_sp1),
                       colour = "white") + # left semicircle
  geom_node_arc_bar(aes(x0 = x,
                        y0 = y,
                        r0 = 0, 
                        r = count/300 + 0.1, 
                        start = 0, 
                        end = pi,
                       fill = rank_sp2),
                       colour = "white") + # right semicircle
  #geom_node_text(aes(label = name)) +                   # "name" is automatically generated from the node IDs in the edges; then adjust r0 o read text
  scale_size(range = c(5, 15),
             guide = "none") +
  scale_edge_linetype_manual(values = c("solid", "dashed"),
                             name = "focal species") +
  scale_fill_gradient2(name = "fitness rank",
                         low = "#5d36f7",
                         high = "#f9db45",
                         mid = "#f274f0",
                         midpoint = mean(ranks_sp1), # to adjust midpoint for landscapes with more or less peaks
                         guide = "colourbar",
                         aesthetics = "fill",
                         transform = "reverse",
                       breaks = c(1, 4, 8, 12, 16)) +
  theme_void() +
  theme(text=element_text(family="Helvetica")) +
  guides(edge_linetype = guide_legend(position = "top"))


ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 15,
       height = 12,
       filename = "graph_NKC_211_2_30.pdf",
       plot = graph)

# ggraph::ggraph(adj_mat) +
#   geom_edge_fan(arrow = arrow(type = "closed",
#                  angle = 20, # "width" of arrow tip
#                  length = unit(4, "mm")), # length of arrow tip
#                  end_cap = circle(4, "mm")) +  
#   geom_node_point(shape = 21, 
#                   stroke = 1,
#                   fill = 'white', 
#                   color = 'black',
#                   size = 7) +
#   theme_void()

````
