---
title: "NKC_exploration"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = "~/OneDrive - Universitaet Bern/NKC_project/R_scripts/") # set directory
```

### Set up workspace
```{r libraries}
rm (list = ls())

library(ggplot2) # for plotting
library(gtools) # permutations to get all possible genotype combinations
library(dplyr) # for constructing the data sets
library(gghalves) # for plotting mixed boxplots with points
library(ggtext) # to get different colour axis titles

# load NKC functions
source(knitr::purl("NKC(S).Rmd", quiet=TRUE)) # this way I load the code from the code chunks in the markdown file

```

# 1) Let's let it rip!!
## 1.1) defining parameters
```{r parameters}
set.seed(1313)

n = 2 # number of loci in each genome
a = 2 # number of alleles at each locus
s = 1 # number of species interacting
s_tot = 2 # total number of species in the community
IM_k_reps = 1 # number of replicates for intragenomic interactions
scape_reps = 50 # number of landscape replicates
fitness_contrib = "N" # distribution from which we draw fitness contributions
fitness_calculation = "KJ" # way to calculate genotype fitness 
fit_mean = 0 # mean of distribution from which we draw fitness contribution
fit_sd = 0.5 # sd of distribution from which we draw fitness contribution
walk_reps = 48 # number of replicates for adaptive walks on a fitness landscape
walk_type = c("greedy", "random", "prop") # types of adaptive walks implemented
walk_start = "S" # where to start the adaptive walks (R - Random, WT - wildtype, S - specified)
max_steps = 100 # max number of steps in the adaptive walk

# defining the starting sequences for N = 2
metatypes_n2 <- gtools::permutations(2, 4, c(1:2), repeats = TRUE)
metaseqs_n2 <- split(metatypes_n2, row(metatypes_n2))
metaseqs_n2 <- lapply(metaseqs_n2, as.numeric)

# defining the starting sequences for N = 4
metatypes_n4 <- gtools::permutations(2, 8, c(1:2), repeats = TRUE)
metaseqs_n4 <- split(metatypes_n4, row(metatypes_n4))
metaseqs_n4 <- lapply(metaseqs_n4, as.numeric)


# defining all the interaction matrices outside the simulations for more reproducibility
## K
IM_k0_n2 <- list(build_IMk(IM = "R",
                      2,
                      0,
                      s,
                      s_tot)) # only one possible layout

IM_k0_n4 <- list(build_IMk(IM = "R",
                      4,
                      0,
                      s,
                      s_tot)) # only one possible layout

IM_k1_n2 <- list(build_IMk(IM = "R",
                      2,
                      1,
                      s,
                      s_tot)) # only one possible layout

IM_k3_n4 <- list(build_IMk(IM = "R",
                      4,
                      3,
                      s,
                      s_tot)) # only one possible layout

# replicates of interaction matrices
# K = 1
IM_k1_n4 <- list()

# random
IM_k1_n4[[1]] <- build_IMk(IM = "R",
                      4,
                      1,
                      s,
                      s_tot)

# modular
IM_k1_n4[[2]] <- build_IMk(IM = "M",
                      4,
                      1,
                      s,
                      s_tot)

# nearest neighbour (but only to one side)
IM_k1_n4[[3]] <- list()
IM_k1_n4[[3]][[1]] <- matrix(c(1,1,0,0,
                               0,1,1,0,
                               0,0,1,1,
                               1,0,0,1), 4, 4, byrow = TRUE)
IM_k1_n4[[3]][[2]] <- matrix(c(1,1,0,0,
                               0,1,1,0,
                               0,0,1,1,
                               1,0,0,1), 4, 4, byrow = TRUE)

# preferential - on average k interactions per locus
IM_k1_n4[[4]] <- build_IMk(IM = "P",
                      4,
                      1,
                      s,
                      s_tot)

# hierarchical - on average k interactions per locus
IM_k1_n4[[5]] <- build_IMk(IM = "H",
                      4,
                      1,
                      s,
                      s_tot)


# K = 2
IM_k2_n4 <- list()

# random
IM_k2_n4[[1]] <- build_IMk(IM = "R",
                      4,
                      2,
                      s,
                      s_tot)

# modular
IM_k2_n4[[2]] <- list()
IM_k2_n4[[2]][[1]] <- matrix(c(1,1,1,0,
                               1,1,1,0,
                               1,1,1,0,
                               0,1,1,1), 4, 4, byrow = TRUE)
IM_k2_n4[[2]][[2]] <- matrix(c(1,1,1,0,
                               1,1,1,0,
                               1,1,1,0,
                               0,1,1,1), 4, 4, byrow = TRUE)

# nearest neighbour
IM_k2_n4[[3]] <- build_IMk(IM = "N",
                      4,
                      2,
                      s,
                      s_tot)

# preferential - on average k interactions per locus
IM_k2_n4[[4]] <- build_IMk(IM = "P",
                      4,
                      2,
                      s,
                      s_tot)

# hierarchical - on average k interactions per locus
IM_k2_n4[[5]] <- build_IMk(IM = "H",
                      4,
                      2,
                      s,
                      s_tot)

## C
IM_c0_n2 <- list(build_IMc(IM = "R",
                      2,
                      0,
                      s,
                      s_tot)) # only one possible layout

IM_c2_n2 <- list(build_IMc(IM = "R",
                      2,
                      2,
                      s,
                      s_tot)) # only one possible layout

IM_c0_n4 <- list(build_IMc(IM = "R",
                      4,
                      0,
                      s,
                      s_tot)) # only one possible layout

# C = 1
IM_c1_n2 <- list()

# symmetric
# only one locus involved in intergenomic epistasis
IM_c1_n2[[1]] <- list()
IM_c1_n2[[1]][[1]] <- matrix(c(1, 1, 0 , 0), 2, 2)
IM_c1_n2[[1]][[2]] <- matrix(c(1, 1, 0 , 0), 2, 2)

# all loci involved in interaction
IM_c1_n2[[2]] <- list()
IM_c1_n2[[2]][[1]] <- matrix(c(1, 0, 0 , 1), 2, 2)
IM_c1_n2[[2]][[2]] <- matrix(c(1, 0, 0 , 1), 2, 2)

# asymmetric 
# all loci involved in interaction
IM_c1_n2[[3]] <- list()
IM_c1_n2[[3]][[1]] <- matrix(c(1, 0, 0 , 1), 2, 2)
IM_c1_n2[[3]][[2]] <- matrix(c(0, 1, 1 , 0), 2, 2)

# all loci involved in interaction for one species; only one locus for the other
IM_c1_n2[[4]] <- list()
IM_c1_n2[[4]][[1]] <- matrix(c(1, 0, 0 , 1), 2, 2)
IM_c1_n2[[4]][[2]] <- matrix(c(1, 1, 0 , 0), 2, 2)
```


# 1.2) running the simulations
```{r simulations}
set.seed(1313)
peaks_nkcs_2121 <- assess_peaks(n, 
                         k = 1,
                         a, 
                         c = 2, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k1_n2,
                         IM_cs = IM_c2_n2,
                         scape_reps = 200, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start,
                         start_seqs = metaseqs_n2,
                         max_steps)

peaks_nkcs_2021 <- assess_peaks(n, 
                         k = 0,
                         a, 
                         c = 2, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k0_n2,
                         IM_cs = IM_c2_n2, 
                         scape_reps = 200, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start, 
                         start_seqs = metaseqs_n2,
                         max_steps)

peaks_nkcs_2111 <- assess_peaks(n, 
                         k = 1,
                         a, 
                         c = 1, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k1_n2,
                         IM_cs = IM_c1_n2, 
                         scape_reps, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start, 
                         start_seqs = metaseqs_n2,
                         max_steps)

peaks_nkcs_2011 <- assess_peaks(n, 
                         k = 0,
                         a, 
                         c = 1, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k0_n2,
                         IM_cs = IM_c1_n2, 
                         scape_reps, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start, 
                         start_seqs = metaseqs_n2,
                         max_steps)

peaks_nkcs_2101 <- assess_peaks(n, 
                         k = 1,
                         a, 
                         c = 0, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k1_n2,
                         IM_cs = IM_c0_n2, 
                         scape_reps = 250, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start, 
                         start_seqs = metaseqs_n2,
                         max_steps)

peaks_nkcs_2001 <- assess_peaks(n, 
                         k = 0,
                         a, 
                         c = 0, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k0_n2,
                         IM_cs = IM_c0_n2,
                         scape_reps = 200, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start,
                         start_seqs = metaseqs_n2,
                         max_steps)

peaks_nkcs_4101 <- assess_peaks(n = 4, 
                         k = 1,
                         a, 
                         c = 0, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k1_n4,
                         IM_cs = IM_c0_n4, 
                         scape_reps, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start,
                         start_seqs = metaseqs_n4, 
                         max_steps)

peaks_nkcs_4201 <- assess_peaks(n = 4, 
                         k = 2,
                         a, 
                         c = 0, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k2_n4,
                         IM_cs = IM_c0_n4,
                         scape_reps, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start,
                         start_seqs = metaseqs_n4,
                         max_steps)

peaks_nkcs_4301 <- assess_peaks(n = 4, 
                         k = 3,
                         a, 
                         c = 0, 
                         s, 
                         s_tot, 
                         IM_ks = IM_k3_n4,
                         IM_cs = IM_c0_n4,
                         scape_reps = 250, 
                         fitness_contrib, 
                         fitness_calculation,
                         fit_mean, 
                         fit_sd, 
                         walk_reps, 
                         walk_type, 
                         walk_start,
                         start_seqs = metaseqs_n4, 
                         max_steps)

peaks_total <- dplyr::bind_rows(peaks_nkcs_4101[[1]],
                                peaks_nkcs_4201[[1]],
                                peaks_nkcs_4301[[1]],
                                peaks_nkcs_2121[[1]],
                                peaks_nkcs_2111[[1]],
                                peaks_nkcs_2101[[1]],
                                peaks_nkcs_2021[[1]],
                                peaks_nkcs_2011[[1]],
                                peaks_nkcs_2001[[1]]) #the bind_rows function allows me to bind dfs with different columns; missing values are filled with NA; this is if I wanted to compare the effect of variable n for example

peaks_total$reached <- peaks_total$fitness == peaks_total$global_peak # I could also just check if rank == 1

# save data
save(peaks_total,
     peaks_nkcs_2121,
      peaks_nkcs_2111,
      peaks_nkcs_2101,
      peaks_nkcs_2021,
      peaks_nkcs_2011,
      peaks_nkcs_2001, file = "peaks_total")

```

## 1.3) summarising the results
```{r}
rm (list = ls())
load("peaks_total")

n = 2
a = 2
s = 1
s_tot = 2
scape_reps = 50
fitness_contrib = "N"
fitness_calculation = "KJ"
fit_mean = 0
fit_sd = 0.5
walk_reps = 48
walk_type = c("greedy", "random")
walk_start = "R"
max_steps = 100

# group simulations by how many species reached their global peak (0/1/2)
peaks_total2 <- as.data.frame(peaks_total |> 
                            dplyr::group_by(k, c, n, k_rep, c_rep, scape_rep, step, walk_rep, walking) |>
                            dplyr::summarise(peaked = sum(reached))) 

# count potential cycles
peaks_total2[peaks_total2$step < max_steps, "pot_cycle"] <- 0 
peaks_total2[peaks_total2$step == max_steps, "pot_cycle"] <- 1 # identify potential cycles

# summarise the adaptive walk replicates
peaks_summarised2 <- as.data.frame(peaks_total2 |> 
                            dplyr::group_by(k, c, n, k_rep, c_rep, scape_rep, walking, peaked) |>
                            dplyr::summarise(peak_count = n(),
                                             cycle_count = sum(pot_cycle)) |>
  tidyr::complete(peaked = 0:2, fill = list(peak_count = 0,
                                            cycle_count = 0))) # add events that did not occur to the df with count 0 to get probabilities of events

# calculate percentages 
peaks_summarised2$tot_reps <- walk_reps
peaks_summarised2$prop_reached <- peaks_summarised2$peak_count/peaks_summarised2$tot_reps
peaks_summarised2$prop_cycled <- peaks_summarised2$cycle_count/peaks_summarised2$tot_reps

# summarise cycling behaviour instead
peaks_summarised_cycles <- as.data.frame(peaks_summarised2 |> 
                            dplyr::group_by(k, c, n, walking, k_rep, c_rep, peaked) |>
                            dplyr::summarise(cycles_count = sum(cycle_count))) 

peaks_summarised_cycles$prop_cycles <- peaks_summarised_cycles$cycles_count/(walk_reps*scape_reps)

# group simulations by peak rank instead
peaks_total_ranked_summarised <- as.data.frame(peaks_total[peaks_total$step < 100,] |> 
                            dplyr::group_by(k, c, n, a, k_rep, c_rep, scape_rep, walking, rank, species) |>
                            dplyr::summarise(rank_peaked = n())) 

peaks_total_cycle_summarised <- as.data.frame(peaks_total[peaks_total$step == 100,] |> 
                            dplyr::group_by(k, c, n, a, k_rep, c_rep, scape_rep, walking, species) |>
                            dplyr::summarise(cycle_count = n())) 
peaks_total_cycle_summarised$rank <- 17

peaks_total_ranked_summarised <- merge(peaks_total_ranked_summarised, 
      peaks_total_cycle_summarised, 
      all.x = TRUE, all.y = TRUE)

# calculate percentages 
peaks_total_ranked_summarised$tot_reps <- walk_reps
peaks_total_ranked_summarised$prop_rank_peaked <- peaks_total_ranked_summarised$rank_peaked/peaks_total_ranked_summarised$tot_reps
peaks_total_ranked_summarised$prop_cycle <- peaks_total_ranked_summarised$cycle_count/peaks_total_ranked_summarised$tot_reps
```

# 2) Exploratory plots
```{r}
### some exploratory plots

# how many species reach the global peak (0/1/2)
ggplot(peaks_summarised2,
        aes(y = prop_reached,
            x = interaction(peaked, n, k, c),
            fill = walking)) +
     geom_boxplot() +
     theme_bw()

# when does cycling occur?
ggplot(peaks_summarised2,
        aes(y = prop_cycled,
            x = interaction(peaked, n, k, c),
            fill = walking)) +
     geom_boxplot() +
     theme_bw()

# how often does cycling occur?
ggplot(peaks_summarised_cycles,
        aes(y = prop_cycles,
            x = interaction(peaked, n, k, c),
            fill = walking)) +
     geom_boxplot() +
     theme_bw()

ggplot(peaks_summarised2[peaks_summarised2$cycle_count > 0,],
        aes(y = prop_cycled,
            x = interaction(n, k, c),
            fill = walking)) +
     geom_boxplot() +
     theme_bw()

# individual replicates reaching peak
ggplot(peaks_summarised2,
        aes(y = prop_reached,
            x = interaction(peaked, n, k, c),
            col = walking)) +
     geom_jitter() +
     theme_bw()

# how many steps in the adaptive walks?
ggplot(peaks_total[peaks_total$reached == TRUE,],
       aes(y = step,
           x = interaction(n, k, c),
           col = walking,
           shape = as.factor(species))) +
  geom_jitter() +
  theme_bw()

ggplot(peaks_total2,
       aes(y = step,
           x = interaction(peaked, n, k, c),
           col = walking)) +
  geom_jitter() +
  theme_bw()

```


# 2.1) plots for manuscript - main results
```{r}
# legends
poster_theme <- theme(axis.text.x.bottom = element_text(size=16),
                        axis.text.y = element_text(size=15),
                        axis.title = element_text(size=24),
                      legend.text = element_text(size=15),
                      legend.title = element_text(size=20),
                      legend.position = "top",
                      strip.text.x = element_text(size = 15),
                      strip.text.y = element_text(size = 15, angle = 0))

  # annotate("text",
  #          x = seq(0.8, 12.8, 1),
  #          y = 1.05,
  #          label = table(peaks_total_ranked_summarised[peaks_total_ranked_summarised$c != 0, c("rank","walking")])[,1],
  #          col = "#157F1F",
  #          vjust = - 1)


big_plot_N2 <- ggplot(peaks_total_ranked_summarised[peaks_total_ranked_summarised$n == 2 &
                                       peaks_total_ranked_summarised$a == 2 &
                                         peaks_total_ranked_summarised$c == 2 &
                                       peaks_total_ranked_summarised$walking == "greedy",],
        aes(y = prop_rank_peaked,
            x = rank,
            group = rank)) +
  geom_bar(aes(y = after_stat(prop), # proportion of data points at each rank (calculated for each facet)
               group = 1),
           fill = "grey85") + # across all my groupings
     geom_violin(col = "grey") +
  geom_violin(aes(y = prop_cycle,
                  x = rank),
              col = "grey") +
  geom_jitter(aes(col = as.factor(c_rep)),
              size = 2.5,
              height = 0.01,
              alpha = 0.4) +
  geom_jitter(aes(y = prop_cycle,
                  x = rank,
                  col = as.factor(c_rep)),
              size = 2.5,
              height = 0.01,
              alpha = 0.4) +
  stat_summary(fun = mean,
               geom = "crossbar", # adds the mean proportion for each rank/landscape
               linewidth = 0.4,
               col = "grey30") +
  stat_summary(aes(y = prop_cycle, # adds the mean proportion of cycling/landscape
                  x = rank),
               fun = mean,
               geom = "crossbar",
               linewidth = 0.4,
               col = "grey30") +
     theme_bw() +
  facet_grid(c ~ k) +
  labs(col = "interaction matrix (C)") +
  scale_x_continuous(labels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "c"),
                     breaks = c(1:17),
                   name = "fitness rank",
                   sec.axis = sec_axis(~ . , name = "K", breaks = NULL, labels = NULL)) +
  scale_y_continuous(name = "<span style='color:grey50'> proportion of overall outcomes </span>  \nproportion of adaptive walks/landscape",
                   sec.axis = sec_axis(~ . , name = "C", breaks = NULL, labels = NULL)) +
  theme(panel.grid.minor.x = element_blank(),
        axis.title.y.right = element_text(angle = 0, vjust = 0.5),
        axis.title.y.left = element_markdown()) +
  poster_theme

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 35,
       height = 20,
       filename = "",
       plot = big_plot_N2)

# looking at differences between the interaction matrices
plot_N2_C1 <- ggplot(peaks_total_ranked_summarised[peaks_total_ranked_summarised$n == 2 &
                                       peaks_total_ranked_summarised$a == 2 &
                                         peaks_total_ranked_summarised$c == 1 &
                                       peaks_total_ranked_summarised$walking == "random",],
        aes(y = prop_rank_peaked,
            x = rank,
            group = rank)) +
  geom_bar(aes(y = after_stat(prop), # proportion of data points at each rank (calculated for each facet)
               group = 1),
           fill = "grey85") + # across all my groupings
     geom_violin(col = "grey") +
  geom_violin(aes(y = prop_cycle,
                  x = rank),
              col = "grey") +
  geom_jitter(aes(col = as.factor(c_rep)),
              size = 2.5,
              height = 0.01,
              alpha = 0.4) +
  geom_jitter(aes(y = prop_cycle,
                  x = rank,
                  col = as.factor(c_rep)),
              size = 2.5,
              height = 0.01,
              alpha = 0.4) +
  stat_summary(fun = mean,
               geom = "crossbar", # adds the mean proportion for each rank/landscape
               linewidth = 0.4,
               col = "grey30") +
  stat_summary(aes(y = prop_cycle, # adds the mean proportion of cycling/landscape
                  x = rank),
               fun = mean,
               geom = "crossbar",
               linewidth = 0.4,
               col = "grey30") +
     theme_bw() +
  facet_grid(c_rep ~ k) +
  labs(col = "interaction matrix (C)") +
  scale_x_continuous(labels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "c"),
                     breaks = c(1:17),
                   name = "fitness rank",
                   sec.axis = sec_axis(~ . , name = "K", breaks = NULL, labels = NULL)) +
  scale_y_continuous(name = "<span style='color:grey50'> proportion of overall outcomes </span>  \nproportion of adaptive walks/landscape",
                   sec.axis = sec_axis(~ . , name = "IM (C)", breaks = NULL, labels = NULL)) +
  theme(panel.grid.minor.x = element_blank(),
        axis.title.y.right = element_text(angle = 0, vjust = 0.5),
        axis.title.y.left = element_markdown()) +
  poster_theme

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 35,
       height = 35,
       filename = "C1_reps_random.pdf",
       plot = plot_N2_C1)

# N = 4
plot_N4 <- ggplot(peaks_total_ranked_summarised[peaks_total_ranked_summarised$n == 4 &
                                       peaks_total_ranked_summarised$walking == "greedy",],
        aes(y = prop_rank_peaked,
            x = rank,
            group = interaction(rank, walking))) +
  geom_bar(aes(y = after_stat(prop), # proportion of data points at each rank (calculated for each facet)
               group = 1),
           fill = "grey85") + # across all my groupings
     geom_violin(col = "grey") +
  geom_jitter(aes(col = as.factor(k_rep)),
              size = 1.5) +
  stat_summary(fun.y = median,
               geom = "crossbar",
               size = 0.3,
               col = "grey30") +
  scale_x_continuous(labels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "cycles"),
                     breaks = c(1:17),
                   name = "fitness rank",
                   sec.axis = sec_axis(~ . , name = "K", breaks = NULL, labels = NULL)) +
  ylab("Proportion of adaptive walks/landscape") +
     theme_bw() +
  facet_grid(k_rep ~ k) +
  labs(col = "interaction matrix (K)") +
  theme(panel.grid.minor = element_blank()) +
  poster_theme

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 35, # 45
       height = 30, # 15
       filename = "K_reps.pdf",
       plot = plot_N4)


```

### 2.1.1) measuring ruggedness
```{r}
# give each landscape a unique ID

peaks_total_ranked_summarised$landscape_ID <- interaction(peaks_total_ranked_summarised$n, peaks_total_ranked_summarised$k, peaks_total_ranked_summarised$c, peaks_total_ranked_summarised$k_rep, peaks_total_ranked_summarised$c_rep, peaks_total_ranked_summarised$scape_rep)

greedy_only <- peaks_total_ranked_summarised[peaks_total_ranked_summarised$walking == "greedy" & 
                                               is.na(peaks_total_ranked_summarised$prop_cycle) &
                                               peaks_total_ranked_summarised$n == 2 &
                                               peaks_total_ranked_summarised$species == 1,]

# how many outcomes are there on the same landscape?
greedy_only_summed <- as.data.frame(greedy_only |> 
                            dplyr::group_by(k, c, n, landscape_ID, ) |>
                            dplyr::summarise(outcomes = n())) 

# K = 1, C = 0
mult_peak <- nrow(greedy_only_summed[greedy_only_summed$k == 1 & 
                            greedy_only_summed$c == 0 &
                            greedy_only_summed$outcomes > 1,]) # tot = 200

# K = 1, C = 1
mult_peak <- nrow(greedy_only_summed[greedy_only_summed$k == 1 & 
                            greedy_only_summed$c == 1 &
                            greedy_only_summed$outcomes > 1,]) # tot = 200

# K = 0, C = 1
mult_peak <- nrow(greedy_only_summed[greedy_only_summed$k == 0 & 
                            greedy_only_summed$c == 1 &
                            greedy_only_summed$outcomes > 1,]) # tot = 200



# joint "community" peaks (peaks for both species together)

## calculate roughness to slope ratio
# fit a linear regression to gentoype - fitness 

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2001[[4]][[1]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_200_1_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(0, length(r)),
                            c = rep(0, length(r)),
                            c_rep = rep(1, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2101[[4]][[1]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_210_1_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(1, length(r)),
                            c = rep(0, length(r)),
                            c_rep = rep(1, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2011[[4]][[1]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_201_1_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(0, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(1, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2011[[4]][[2]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_201_2_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(0, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(2, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2011[[4]][[3]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_201_3_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(0, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(3, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2011[[4]][[4]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_201_4_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(0, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(4, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2011[[4]][[5]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_201_5_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(0, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(5, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)


r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2111[[4]][[1]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_211_1_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(1, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(1, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2111[[4]][[2]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_211_2_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(1, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(2, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2111[[4]][[3]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_211_3_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(1, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(3, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2111[[4]][[4]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))

}

ruggedness_nkc_rep_sp_211_4_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(1, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(4, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            rugg = r/s)

r <- NULL
s <- NULL
s_k <- NULL
s_c <- NULL

for (i in 1:50) {
  
  temp_landscape <- peaks_nkcs_2111[[4]][[5]][[i]][[1]]
  linear_model <- lm(temp_landscape$fitness ~ temp_landscape$F.1 + temp_landscape$F.2 + temp_landscape$P.1 + temp_landscape$P.2)
  
  r <- c(r, var(linear_model$residuals))
  s <- c(s, mean(linear_model$coefficients[-1]))
  
  s_k <- c(s_k, sum(linear_model$coefficients[c(2,3)]))
  s_c <- c(s_c, sum(linear_model$coefficients[c(4,5)]))
  
  

}

ruggedness_nkc_rep_sp_211_5_1 <- data.frame(n = rep(2, length(r)),
                            k = rep(1, length(r)),
                            c = rep(1, length(r)),
                            c_rep = rep(5, length(r)),
                            sp = rep(1, length(r)),
                            r = r,
                            s = s,
                            c_vs_k = s_c/s_k,
                            rugg = r/s)

ruggedness_df <- rbind(ruggedness_nkc_rep_sp_200_1_1, ruggedness_nkc_rep_sp_201_1_1, ruggedness_nkc_rep_sp_201_2_1, ruggedness_nkc_rep_sp_201_3_1, ruggedness_nkc_rep_sp_201_4_1, ruggedness_nkc_rep_sp_201_5_1, ruggedness_nkc_rep_sp_210_1_1, ruggedness_nkc_rep_sp_211_1_1, ruggedness_nkc_rep_sp_211_2_1, ruggedness_nkc_rep_sp_211_3_1, ruggedness_nkc_rep_sp_211_4_1, ruggedness_nkc_rep_sp_211_5_1)

ruggedness_df$rugg <- abs(ruggedness_df$rugg)
ruggedness_df$rugg <- round(ruggedness_df$rugg, 4)

ggplot(ruggedness_df,
       aes(x = interaction(n, k, c),
           y = rugg,
           group = interaction(n, k, c, c_rep))) +
  geom_boxplot(aes(col = as.factor(c_rep))) +
  scale_y_log10() + 
  ylab("log(roughness/slope)")+
  theme_bw()

```

## 2.2) Plots I put on my GRS/GRC poster
``` {r Poster figures}

legend <- scale_colour_manual(values = c("#157F1F", "#FCA311", "#CB48B7"),
                              breaks = c("greedy","prop", "random"),
                              labels = c("greedy",
                                         "weighted",
                                         "random"),
                              name="type of adaptive walk")

poster_theme <- theme(axis.text.x.bottom = element_text(size=16),
                        axis.text.y = element_text(size=15),
                        axis.title = element_text(size=25),
                      legend.text = element_text(size=15),
                      legend.title = element_text(size=20),
                      legend.position = "top")

peak_fig <- ggplot(peaks_summarised2[peaks_summarised2$peaked == 2,],
        aes(y = prop_reached,
            x = interaction(n, k, c),
            col = walking)) +
     gghalves::geom_half_boxplot(nudge = 0.05,
                                 fill = "grey90") +
  gghalves::geom_half_point(position = "dodge2",
                            transformation = position_jitter(w = 0.05, h = 0)) +
  scale_x_discrete(labels=c("2.0.0" = "2-0-0", 
                            "2.1.0" = "2-1-0",
                            "2.0.1" = "2-0-1",
                            "2.1.1" = "2-1-1",
                            "2.0.2" = "2-0-2",
                            "2.1.2" = "2-1-2")) +
  ylab("Probability of both species reaching their global peak") +
  xlab("N-K-C") +
  legend +
  theme_bw() +
  poster_theme +
  theme(axis.title.y = element_text(size = 22))

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 26,
       height = 18.5,
       filename = "peak_fig.pdf",
       plot = peak_fig)

step_fig <- ggplot(peaks_total2,
       aes(y = step,
           x = interaction(peaked, n, k, c),
           col = walking)) +
  gghalves::geom_half_boxplot(nudge = 0.05,
                                 fill = "grey80") +
  gghalves::geom_half_point(position = "dodge2",
                            transformation = position_jitter(w = 0.05, h = 0)) +
  scale_x_discrete(labels=c("2.2.0.0" = "2-0-0~2", 
                            "0.2.1.0" = "2-1-0~0",
                            "1.2.1.0" = "2-1-0~1",
                            "2.2.1.0" = "2-1-0~2",
                            "0.2.0.1" = "2-0-1~0",
                            "1.2.0.1" = "2-0-1~1",
                            "2.2.0.1" = "2-0-1~2",
                            "0.2.1.1" = "2-1-1~0",
                            "1.2.1.1" = "2-1-1~1",
                            "2.2.1.1" = "2-1-1~2",
                            "0.2.0.2" = "2-0-2~0",
                            "1.2.0.2" = "2-0-2~1",
                            "2.2.0.2" = "2-0-2~2",
                            "0.2.1.2" = "2-1-2~0",
                            "1.2.1.2" = "2-1-2~1",
                            "2.2.1.2" = "2-1-2~2")) +
  ylab("Steps in adaptive walk") +
  xlab("N-K-C ~ nb. of species at global peak") +
  legend +
  theme_bw() +
  poster_theme

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 45,
       height = 18,
       filename = "step_fig.pdf",
       plot = step_fig)

cycle_fig <- ggplot(peaks_summarised_cycles,
        aes(y = prop_cycles,
            x = interaction(n, k, c),
            col = walking)) +
  gghalves::geom_half_boxplot(nudge = 0.05,
                                 fill = "grey80") +
  gghalves::geom_half_point(position = "dodge2",
                            transformation = position_jitter(w = 0.05, h = 0)) +
  scale_x_discrete(labels=c("2.0.0" = "2-0-0", 
                            "2.1.0" = "2-1-0",
                            "2.0.1" = "2-0-1",
                            "2.1.1" = "2-1-1",
                            "2.0.2" = "2-0-2",
                            "2.1.2" = "2-1-2")) +
  ylab("Probability of cycling") +
  xlab("N-K-C") +
  legend +
  theme_bw() +
  poster_theme

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 26,
       height = 18,
       filename = "cycle_fig.pdf",
       plot = cycle_fig)

example_scape_fig <- visualise_system(peaks_nkcs_2111[[4]][[2]][[40]], # this is just a pair of landscapes I chose because they lead to cycling
                 n,
                 c,
                 s,
                 s_tot) +
  theme(axis.text.x.bottom = element_text(size=16),
                        axis.text.y = element_text(size=15),
                        axis.title = element_text(size=25 ),
        strip.text.x = element_text(size=25))

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 35,
       height = 14,
       filename = "scapes_NKC_211_2_40.pdf",
       plot = example_scape_fig)

walks_fig <- visualise_walks(peaks_nkcs_2111[[5]][[5]][[22]][[1]][[28]], # these are the adaptive walks (cycling) that go with the example I chose (greedy walk)
                n,
                s,
                s_tot,
                peaks_nkcs_2111[[4]][[5]][[22]]) + # this is the matching pair of landscapes
  theme(axis.text.x.bottom = element_text(size=16),
                        axis.text.y = element_text(size=15),
                        axis.title = element_text(size=25),,
        strip.text.x = element_text(size=25))

ggsave(path = "../Figures/",
       device = "pdf",
       units = c("cm"),
       width = 30,
       height = 14,
       filename = "walks_fig.pdf",
       plot = walks_fig)
 
```

 
## 3) Trying some linear models
```{r}

test_data1 <- peaks_total_ranked_summarised[peaks_total_ranked_summarised$n == 2 &
                                       peaks_total_ranked_summarised$a == 2 &
                                       peaks_total_ranked_summarised$walking == "greedy",]

test_data <- peaks_total[peaks_total$n == 2 &
                         peaks_total$a == 2 &
                           peaks_total$c != 2 &
                           peaks_total$walking == "greedy" &
                           peaks_total$step < 100,]

test_data3 <- peaks_total[peaks_total$n == 2 &
                         peaks_total$a == 2 &
                           peaks_total$walking == "greedy",]

test_data3$cycle <- "N"
test_data3[test_data3$step == 100, "cycle"] <- "Y"

library(nnet)
library(broom)

# the effect of C/K on the final rank
model <- nnet::multinom(as.factor(rank) ~ as.factor(k) * as.factor(c), data = test_data)
#sum_mod <- summary(model)

coef_df <- broom::tidy(model) %>%
  mutate(
    OR  = exp(estimate),                 # odds ratio
    OR_low  = exp(estimate - 1.96*std.error), # 95% CI lower
    OR_high = exp(estimate + 1.96*std.error)  # 95% CI upper
  )  %>%
  filter(term != "(Intercept)") %>%      # drop intercepts
  mutate(predictor = term,
         Rank   = factor(y.level, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16")))

ggplot(coef_df, 
       aes(x = predictor, 
           y = OR, 
           color = Rank)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey40") +
  geom_point(position = position_dodge(width = 0.7), 
             size = 3) +
  geom_errorbar(aes(ymin = OR_low, 
                    ymax = OR_high),
                width = 0.2,
                position = position_dodge(width = 0.7)) +
  scale_y_log10() +   # << log-transformed axis
  theme_bw(base_size = 14) +
  labs(y = "log(Odds ratio)", x = "") +
  scale_x_discrete(labels = c("as.factor(c)1" = "C = 1",
                              "as.factor(k)1" = "K = 1",
                              "as.factor(k)1:as.factor(c)1" = "C = 1:K = 1")) 

model_cycle <- glm(as.factor(cycle) ~ as.factor(k) * as.factor(c) * as.factor(c_rep),
             data = test_data3,
             family = binomial(link = "logit"))

coef_df <- broom::tidy(model_cycle) %>%
  mutate(
    OR  = exp(estimate),                 # odds ratio
    OR_low  = exp(estimate - 1.96*std.error), # 95% CI lower
    OR_high = exp(estimate + 1.96*std.error)  # 95% CI upper
  )  %>%
  filter(term != "(Intercept)") 

ggplot(coef_df, 
       aes(x = term, 
           y = OR)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey40") +
  geom_point(position = position_dodge(width = 0.7), 
             size = 3) +
  geom_errorbar(aes(ymin = OR_low, 
                    ymax = OR_high),
                width = 0.2,
                position = position_dodge(width = 0.7)) +
  scale_y_log10() +   # << log-transformed axis
  theme_bw(base_size = 14) +
  labs(y = "log(Odds ratio)", x = "") +
  scale_x_discrete(labels = c("as.factor(c)1" = "C = 1",
                              "as.factor(c)2" = "C = 2",
                              "as.factor(k)1" = "K = 1",
                              "as.factor(k)1:as.factor(c)1" = "C = 1:K = 1",
                              "as.factor(k)1:as.factor(c)2" = "C = 2:K = 1")) 


```